/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyRouteImport } from './routes/why'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CollegesIdRouteImport } from './routes/colleges.$id'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMyEventsRouteImport } from './routes/app.my-events'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppBookmarksRouteImport } from './routes/app.bookmarks'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as EventsIdRegisterRouteImport } from './routes/events_.$id.register'
import { Route as ArenaPlayRoomIdRouteImport } from './routes/arena.play.$roomId'
import { Route as ArenaHostRoomIdRouteImport } from './routes/arena.host.$roomId'
import { Route as AppEventsIdRouteImport } from './routes/app.events.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIdRoute = CollegesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CollegesRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyEventsRoute = AppMyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsIdRegisterRoute = EventsIdRegisterRouteImport.update({
  id: '/events_/$id/register',
  path: '/events/$id/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaPlayRoomIdRoute = ArenaPlayRoomIdRouteImport.update({
  id: '/play/$roomId',
  path: '/play/$roomId',
  getParentRoute: () => ArenaRoute,
} as any)
const ArenaHostRoomIdRoute = ArenaHostRoomIdRouteImport.update({
  id: '/host/$roomId',
  path: '/host/$roomId',
  getParentRoute: () => ArenaRoute,
} as any)
const AppEventsIdRoute = AppEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/arena': typeof ArenaRouteWithChildren
  '/colleges': typeof CollegesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/why': typeof WhyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/create': typeof AppCreateRoute
  '/app/my-events': typeof AppMyEventsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/arena/host/$roomId': typeof ArenaHostRoomIdRoute
  '/arena/play/$roomId': typeof ArenaPlayRoomIdRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arena': typeof ArenaRouteWithChildren
  '/colleges': typeof CollegesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/why': typeof WhyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/create': typeof AppCreateRoute
  '/app/my-events': typeof AppMyEventsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/app': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/arena/host/$roomId': typeof ArenaHostRoomIdRoute
  '/arena/play/$roomId': typeof ArenaPlayRoomIdRoute
  '/events/$id/register': typeof EventsIdRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/arena': typeof ArenaRouteWithChildren
  '/colleges': typeof CollegesRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/practice': typeof PracticeRoute
  '/search': typeof SearchRoute
  '/why': typeof WhyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/bookmarks': typeof AppBookmarksRoute
  '/app/create': typeof AppCreateRoute
  '/app/my-events': typeof AppMyEventsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/events/$id': typeof EventsIdRoute
  '/app/': typeof AppIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/events/$id': typeof AppEventsIdRoute
  '/arena/host/$roomId': typeof ArenaHostRoomIdRoute
  '/arena/play/$roomId': typeof ArenaPlayRoomIdRoute
  '/events_/$id/register': typeof EventsIdRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/arena'
    | '/colleges'
    | '/discover'
    | '/explore'
    | '/login'
    | '/mcp'
    | '/practice'
    | '/search'
    | '/why'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/bookmarks'
    | '/app/create'
    | '/app/my-events'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/colleges/$id'
    | '/events/$id'
    | '/app/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/events/$id'
    | '/arena/host/$roomId'
    | '/arena/play/$roomId'
    | '/events/$id/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arena'
    | '/colleges'
    | '/discover'
    | '/explore'
    | '/login'
    | '/mcp'
    | '/practice'
    | '/search'
    | '/why'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/bookmarks'
    | '/app/create'
    | '/app/my-events'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/colleges/$id'
    | '/events/$id'
    | '/app'
    | '/.mcp/invoke-tool/$tool'
    | '/app/events/$id'
    | '/arena/host/$roomId'
    | '/arena/play/$roomId'
    | '/events/$id/register'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/arena'
    | '/colleges'
    | '/discover'
    | '/explore'
    | '/login'
    | '/mcp'
    | '/practice'
    | '/search'
    | '/why'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/bookmarks'
    | '/app/create'
    | '/app/my-events'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/colleges/$id'
    | '/events/$id'
    | '/app/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/events/$id'
    | '/arena/host/$roomId'
    | '/arena/play/$roomId'
    | '/events_/$id/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ArenaRoute: typeof ArenaRouteWithChildren
  CollegesRoute: typeof CollegesRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PracticeRoute: typeof PracticeRoute
  SearchRoute: typeof SearchRoute
  WhyRoute: typeof WhyRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EventsIdRoute: typeof EventsIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  EventsIdRegisterRoute: typeof EventsIdRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$id': {
      id: '/colleges/$id'
      path: '/$id'
      fullPath: '/colleges/$id'
      preLoaderRoute: typeof CollegesIdRouteImport
      parentRoute: typeof CollegesRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-events': {
      id: '/app/my-events'
      path: '/my-events'
      fullPath: '/app/my-events'
      preLoaderRoute: typeof AppMyEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookmarks': {
      id: '/app/bookmarks'
      path: '/bookmarks'
      fullPath: '/app/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id/register': {
      id: '/events_/$id/register'
      path: '/events/$id/register'
      fullPath: '/events/$id/register'
      preLoaderRoute: typeof EventsIdRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena/play/$roomId': {
      id: '/arena/play/$roomId'
      path: '/play/$roomId'
      fullPath: '/arena/play/$roomId'
      preLoaderRoute: typeof ArenaPlayRoomIdRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/arena/host/$roomId': {
      id: '/arena/host/$roomId'
      path: '/host/$roomId'
      fullPath: '/arena/host/$roomId'
      preLoaderRoute: typeof ArenaHostRoomIdRouteImport
      parentRoute: typeof ArenaRoute
    }
    '/app/events/$id': {
      id: '/app/events/$id'
      path: '/events/$id'
      fullPath: '/app/events/$id'
      preLoaderRoute: typeof AppEventsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppCreateRoute: typeof AppCreateRoute
  AppMyEventsRoute: typeof AppMyEventsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEventsIdRoute: typeof AppEventsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppCreateRoute: AppCreateRoute,
  AppMyEventsRoute: AppMyEventsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEventsIdRoute: AppEventsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ArenaRouteChildren {
  ArenaHostRoomIdRoute: typeof ArenaHostRoomIdRoute
  ArenaPlayRoomIdRoute: typeof ArenaPlayRoomIdRoute
}

const ArenaRouteChildren: ArenaRouteChildren = {
  ArenaHostRoomIdRoute: ArenaHostRoomIdRoute,
  ArenaPlayRoomIdRoute: ArenaPlayRoomIdRoute,
}

const ArenaRouteWithChildren = ArenaRoute._addFileChildren(ArenaRouteChildren)

interface CollegesRouteChildren {
  CollegesIdRoute: typeof CollegesIdRoute
}

const CollegesRouteChildren: CollegesRouteChildren = {
  CollegesIdRoute: CollegesIdRoute,
}

const CollegesRouteWithChildren = CollegesRoute._addFileChildren(
  CollegesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ArenaRoute: ArenaRouteWithChildren,
  CollegesRoute: CollegesRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PracticeRoute: PracticeRoute,
  SearchRoute: SearchRoute,
  WhyRoute: WhyRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EventsIdRoute: EventsIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  EventsIdRegisterRoute: EventsIdRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
